import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import Logo from '../public/vercel.svg'
import ProjectLogo from '../public/api.jpg'
import AnotherLogo from '../public/holder.jpg'
import Link from 'next/link'
import {Twitter, Linkedin, GitHub, Twitch, Instagram} from 'react-feather'
import DateTime from './components/dateTime'
import {format} from 'date-fns'
import Contact from './components/contact'
import { Canvas} from '@react-three/fiber'
import { AmbientLight } from 'three'
import Box from './main'

export default function Home({data}) {        
  const Competencies = ['Javascript', "Python", "React", "NextJS", "Linux","MySQL","MongoDB", "Agile Methodologies", " Node.js", "Server Administration","Express", "Amazon Web Services (AWS)","Automated Testing (Cypress)"]                                                                        
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter"/>
      </Head>
      {/* Navigation Bar */}
      <div className={styles.headerWrapper}>
        <div className={styles.siteDate}><DateTime/></div>
      <div className={styles.navbar}>
          <div className={styles.brand}>
              <Image src={Logo} alt='Site Logo'/>
            </div>
            <div className={styles.navigation}>
              <Link href='/'>Home</Link>
              <Link href='#about'>About</Link>
              <Link href='/'>Portfolio</Link>
              <Link href='/'>Contact</Link>
              <Link href='/'>Blog</Link>
            </div>
        </div>
        <div className={styles.header}>
          <div className={styles.bioCard}>
            <Image className={styles.bioImage} src={data.avatar_url} height={96} width={96} alt='User Photo' priority />
            <h5>{data.name}</h5><br/>
            <hr/>
            <p>{data.bio}</p><br/>
            <p>Github Repos: {data.public_repos}</p>
            <p>Location: {data.location}</p>
            <hr/>
            <div className={styles.socialIcons}>
              <div className={styles.twitter}><Link href='https://twitter.com/_son_of_morning' target='_blank'><Twitter/></Link></div>
              <div className={styles.linkedin}><Link href='https://www.linkedin.com/in/bevon-ochieng-579008166/' target='_blank'><Linkedin/></Link></div>
              <div className={styles.github}><Link href='https://github.com/Bevon' target='_blank'><GitHub/></Link></div>
            </div>
          </div>
        </div>
      </div>
       
      {/* The flexible grid (content) */}
      <div className={styles.row}>
        
        
        <div className={styles.side}>
          <h5>Skills & Core Competencies</h5>
          <hr/>
          <div className={styles.skills}>
            {
              Competencies.map(function(skill, id){
                return (
                  <div className={styles.column} key={id}>
                    {skill}
                  </div>
                )
              })
            }
          </div>
          <div>
            <Canvas>
                <ambientLight/>
                <pointLight position={[10, 10, 10]} />
                <Box position={[-1.2, 0, 0]} />
                <Box position={[1.2, 0, 0]} />
            </Canvas>
      </div>
        </div>
        <div className={styles.main}>
          <h2>My Creative Portfolio</h2>
          <h5>These are some of the project I have built with my skills</h5>
          <div className={styles.projects}>
            <div className={styles.projectCard}>
              <div className={styles.imageCard}>
              <Image src={ProjectLogo} alt='Project Image' height={128} style={{backgroundSize:'cover'}}/>
              </div>
              <h5>E-Commerce Web App</h5>
              <p>Some quick example text to build on the card title and make up the bulk of the card's content</p>
              <Link href={'/'} target='_blank'>View Project</Link>
              <div className={styles.techCardContainer}>
              <div className={styles.techCard}>Python</div>
              <div className={styles.techCard}>Django</div>
              <div className={styles.techCard}>React</div>
              </div>
            </div>
            <div className={styles.projectCard}>
            <div className={styles.imageCard}>
              <Image src={AnotherLogo} alt='Project Image' height={128} style={{backgroundSize:'cover'}}/>
              </div>
              <h5>Random Quote Machine</h5>
              <p>Some quick example text to build on the card title and make up the bulk of the card's content</p>
              <Link href={'/'} target='_blank'>View Project</Link>
              <div className={styles.techCardContainer}>
              <div className={styles.techCard}>React</div>
              <div className={styles.techCard}>Node.js</div>
              <div className={styles.techCard}>Express</div>
              </div>
            </div>
            <div className={styles.projectCard}>
            <div className={styles.imageCard}>
              <Image src={ProjectLogo} alt='Project Image' height={128} style={{backgroundSize:'cover'}}/>
              </div>
              <h5>Car Hire Service App</h5>
              <p>Some quick example text to build on the card title and make up the bulk of the card's content</p>
              <a href='/'>View Project</a>
              <div className={styles.techCardContainer}>
              <div className={styles.techCard}>React</div>
              <div className={styles.techCard}>Node.js</div>
              <div className={styles.techCard}>Express</div>
              </div>
            </div>
            <div className={styles.projectCard}>
            <div className={styles.imageCard}>
              <Image src={ProjectLogo} alt='Project Image' height={128} style={{backgroundSize:'cover'}}/>
              </div>
              <h5>Tech Blog Website</h5>
              <p>Some quick example text to build on the card title and make up the bulk of the card's content</p>
              <Link href={'/'} target='_blank'>View Project</Link>
              <div className={styles.techCardContainer}>
              <div className={styles.techCard}>NextJS</div>
              <div className={styles.techCard}>Node.js</div>
              <div className={styles.techCard}>Tailwind</div>
              </div>
            </div>
          </div>
        </div>
      </div>
      

      {/* <!-- Footer --> */}
      <div className={styles.footer}>
        <div>
          <div>
            <div className={styles.aboutSite}>
              <h3>Rubric</h3>
              <Image src={Logo} alt='Site Logo'/>
              <p>This is a child container.This is a child container.
              This is a child container.This is a child container.This is a child container</p>
            </div>
          </div>
        </div>
        <div>
        <div>
            <div className={styles.aboutSite}>
              <h3>Useful Links</h3>
              <div className={styles.usefulLink}>
                <div className={styles.icons}><Link href={'/'}><GitHub/></Link></div>
                <div><a>Github Repositories</a></div>
              </div>
              <div className={styles.usefulLink}>
                <div className={styles.icons}><Link href={'/'}><Twitter/></Link></div>
                <div><Link href={'/'}>Follow me on twitter</Link></div>
              </div>
              <div className={styles.usefulLink}>
                <div className={styles.icons}><Link href={'/'}><Linkedin/></Link></div>
                <div><Link href={'/'}>Follow me on Linkedin</Link></div>
              </div>
              <div className={styles.usefulLink}>
                <div className={styles.icons}><Link href={'/'}><Twitch/></Link></div>
                <div><Link href={'/'}>Follow me on Twitch</Link></div>
              </div>
              <div className={styles.usefulLink}>
                <div className={styles.icons}><Link href={'/'}><Instagram/></Link></div>
                <div><Link href={'/'}>Follow me on Instagram</Link></div>
              </div>
            </div>
          </div>
        </div>
        <div>
        <div>
            <div className={styles.aboutSite}>
              <h3>Contact Me</h3>
              <Contact/>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.copyright}>
        <p><copyright>{format(new Date(Date.now()), 'MMMM yyyy')}. All rights reserved.</copyright></p>
      </div>
    </>
  )
}

export async function getStaticProps(){
  const res = await fetch('https://api.github.com/users/Bevon');
  if (!res.ok){
    throw new Error('Resource not found')
  }
  const data = await res.json();
  return {
    props : {data}
  }
}
